### ISSUE TITLE
Add OpenGraph Metadata to site, entries

### ISSUE THREAD

**Issue by allanwhite** [OriginalEXE/contentmodel.io-web#3]
When the site URL is shared, or a content model is shared, some opengraph metadata and image preview would make that a better experience. 

- [x] Add basic OG meta to site, entries
- [x] Add OG image card to main landing page (can be static) _Happy to help with this one_
- [x] Figure out a way to render an image of the model and bake it into a cool card. Cloudinary, or PhantomJS, or something.

Proposed card design (figma [artwork](https://www.figma.com/file/KEcUTT3NMA1MMGCMXIV9IA/ContentModel.io-graphics?node-id=0%3A1)):
![image](https://user-images.githubusercontent.com/887931/107587290-4a516400-6bb6-11eb-8581-9ae0e7873458.png)

**Comment by OriginalEXE** [comment]
Hey Allan, thanks for opening this.

This is indeed an important feature to tackle, thanks for the card design, I love it. I am soon going to be tackling this, together with exporting the content model as an image since both will be relying on the ability to generate images out of content models.

**Comment by OriginalEXE** [comment]
This is now implemented, thank you for the card inspiration 🙇🏻
