### ISSUE TITLE
Not able to use Visualize content model

### ISSUE THREAD

**Issue by jeremyrich** [OriginalEXE/contentmodel.io-web#5]
Hello, 

I have tried multiple time to Visualize content model either from **Pull from contentfull** or **Copy/Paste** but was not able to go up to the end. 

- Pull from content : connection is working. I can select my space en environment but then run into `Could not fetch the content model from the API. Check that you have provided the correct details.`

- Copy/Paste : I have exported my content models from contentful CLI but when I tried to Validate and Continue I run into `We could not parse the JSON provided, copy-paste the full JSON as exported via either Contentful CLI or the Delivery API`

Please let me know, what information you need to debug it ?

**Comment by OriginalEXE** [comment]
Hello,

Thanks a lot for sharing the issue and sorry that you are experiencing it in the first place.

What would help is having a content model at hand that's causing this. Is this something you would be comfortable sharing with me? If you want to keep it private, you could send it to hello@contentmodel.io

Thank you

**Comment by jeremyrich** [comment]
replied by email, thank you

**Comment by OriginalEXE** [comment]
Hey Jeremy, closing this issue as it's hopefully solved now (just replied to you via email with the details).

For anyone curious, my content model validation was too strict, expecting `displayField` to always be a string.

Feel free to re-open if the issue persists.

Thanks again for reporting it and using the service,
Ante
